version: '3'
services:
  cassandra:
    image: cassandra:3.9
    container_name: kong-tests-cassandra
    ports:
      - "127.0.0.1:9042:9042"

  postgres:
    build: ./postgres
    container_name: kong-tests-postgres
    command: postgres -c "config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - "$PWD/postgres/postgres.conf:/etc/postgresql/postgresql.conf"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    image: redis
    container_name: kong-tests-redis
    ports:
      - "127.0.0.1:6379:6379"

  grpcbin:
    image: moul/grpcbin
    container_name: kong-tests-grpcbin
    ports:
      - "127.0.0.1:15002:9000"
      - "127.0.0.1:15003:9001"
